### ISSUE TITLE
SchemaLoader uses hard coded Unix path separator

### ISSUE THREAD

**Issue by tonvanbart** [Axual/ksml#105]
Class `SchemaLoader` has a hard coded constant `DIRECTORY_SEPARATOR` set to `/`, which will probably fail if someone tries to run KSML on a Windows system. Replacing this with `File.pathSeparator()` or similar would be more robust.
I did not check if there are other locations in the code with similar constants.

**Comment by richard-axual** [comment]
@tonvanbart Good find
But even if you run the image on a windows system, it would still use the unix style filesystem internally.
So for a runner I don't expect a problem here.

I expect this to be a problem only if someone builds KSML from code on a windows machine.
Which will happen sooner or later of course.
Let's look at this after the 1.0.0 release
