### ISSUE TITLE
Dynamic output to topics by value?

### ISSUE THREAD

**Issue by 0123hoang** [Axual/ksml#20]
I'm quite familiar at kafka, kafka connect and new with ksml. \
Is there a way that output topics can be caculated by value of message (in schema), or some function?

**Comment by jeroenvandisseldorp** [comment]
Yes, you can use the ToTopicNameExtractor operator to dynamically route messages to a specific target topic. Is that what you are looking for?

**Comment by 0123hoang** [comment]
thank you, i'll try it.
